name: Update Impact Meter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch data from Google Apps Script
        run: |
          curl -s "https://script.google.com/macros/s/AKfycbDYcRc67iGbVU_jYfL5iEwpemWUy2UvM0WlHAvmKc5DTj51ThpeHLce_uo748cSOSKoA/exec" -o data.json

      - name: Commit and push
        run: |
          git config user.name "Impact Meter Bot"
          git config user.email "bot@impactmeter.local"

          git add data.json
          git commit -m "Auto-update meter data" || echo "No changes to commit"

          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/timmybomb/impact-meter.git
